### ISSUE TITLE
Does it support UTC time?

### ISSUE THREAD

**Issue by jona-hsueh** [tarutin/hovrly#1]
Sorry to leave feedback in here, seems it doesn't support UTC time. It's very popular for system and operation engineers, could you add this feature ?

**Comment by tarutin** [comment]
@jona-hsueh Hi!
Hovrly use the system time.

**Comment by alapolloni** [comment]
He means adding UTC as an option since search only seems to have cities..   (As a workaround, I added a city from this list   : https://en.wikipedia.org/wiki/UTC±00:00#As_standard_time_(year-round)   (IE: Reykjavik, ICELAND)  @jona-hsueh )

**Comment by tarutin** [comment]
@jona-hsueh @alapolloni Thanks for feedback! I've added UTC+0 in city list. Just search 'UTC'.
