### ISSUE TITLE
VPN: Unable To Connect To DB

### ISSUE THREAD

**Issue by hunoz** [tarutin/hovrly#10]
I am unable to connect to the database. I am basing this off of my inability to search for a city, so I pulled the repo and started it locally. Below is what it output:
```

> hovrly@2.4.3 start
> DEV=true electron .

index init
window init
menu init
tray init
launch init
clock init
updater init
notice init
db init
init: 886.657ms
db lost connect
db lost connect
db lost connect
db lost connect
```

I know that https://github.com/tarutin/hovrly/issues/3 was opened in regards to this, however my situation is a little different. I believe the cause to be due to AWS IPs being blocked. Unfortunately, in my daily work, I need to VPN, which is hosted in AWS. Is it possible to unblock AWS IPs or allow some sort of proxy setup?

**Comment by hunoz** [comment]
For reference, I am basing my theory on it being AWS IP blocking due to the numerous other companies/websites that will outright block AWS IPs, so I un-VPN, and then it works, which was the case with this as I tested on my local network and it worked fine.

**Comment by tarutin** [comment]
@stonedprogrammer Hm. This is interesting case. Let me think about it. One of the solutions: to transfer cities DB to app locally on MongoDB or something, but this solution is difficult for updates...

**Comment by hunoz** [comment]
I'm unfamiliar with your application's architecture, but perhaps opening to AWS IPs but placing a firewall in front of the DB would help? If an IP reaches out too many times too quickly, it gets blocked. Something akin to fail2ban?

**Comment by gabek** [comment]
Since cities and timezones don't change _that_ often, maybe just export the entire DB and bundle it with the application so you don't have to maintain a server for an application that doesn't have any online connectivity requirements.

**Comment by saphid** [comment]
> @stonedprogrammer Hm. This is interesting case. Let me think about it. One of the solutions: to transfer cities DB to app locally on MongoDB or something, but this solution is difficult for updates...

ah yep this. Ohh IANA has a list. that's nice.
https://www.iana.org/time-zones

and world time server.
https://www.worldtimeserver.com/time_zone_guide/documentation/

And seems like you can get a mail when there is an update, so maybe you can have something consume that mail or something. You are smarter than me so I assume you'll find something good

**Comment by tarutin** [comment]
@stonedprogrammer Hi!
Please check new version [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
