### ISSUE TITLE
Feature Request: Ability to rename the time zone.

### ISSUE THREAD

**Issue by PukarGh** [tarutin/hovrly#12]
It would be great if we have an ability to rename the timezone name. For example, the Chicago, US timezone is commonly referred to as the Central Time (CT) and the New York, US time is referred to as Eastern Time (ET). It would be nice if users could rename the timezones as per their convenience.

**Comment by tarutin** [comment]
Added in [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
