### ISSUE TITLE
Is it supposed to stick to the upper left corner of the monitor?

### ISSUE THREAD

**Issue by peterinjapan** [tarutin/hovrly#13]
Nice app idea, but it's neither a menu bar app nor a window I can position. For me, on a modern M1 Macbook Pro, the window is in the upper left-hand corner and cannot be moved. I have a giant 55 inch monitor and this is very hard for me, as I literally cannot read the letters without moving my head.

Also, needs a Settings panel, and some of the options should be hidden in there rather than visible all the time. Also, there is zero contact info for the creators on the website, nor any social media, yet they ask for feedback and ideas from users.

**Comment by tarutin** [comment]
@peterinjapan Hi! thank you for feedback! Can you attach screenshot?

**Comment by mrjoecastellon** [comment]
I am having the same issue. The main window sticks to the upper left portion of the screen and I see no way of dragging it around. It doesn't show on my menu bar either 🤔 
![image](https://user-images.githubusercontent.com/91094235/195141575-b91a15cc-9727-46ba-9b47-c87bc6c25927.png)

**Comment by tarutin** [comment]
@peterinjapan @mrjoecastellon I'll check it!

**Comment by tarutin** [comment]
Fixed: [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
@peterinjapan  Please, check it again
