### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by saphid** [tarutin/hovrly#14]
When typing a city name in nothing happens. Reading the code it seems like the search should start happening on key up.

When I type I get zero visual feedback.

Tried: Sydney, London, Seattle, Zurich, Tokyo, Canberra

**Comment by saphid** [comment]
Mac OS: 12.3.1
MacBook Pro (16-inch, 2019)

**Comment by tarutin** [comment]
@saphid Hi! Thanks for feedback!
Please try again and read my comment here: https://github.com/tarutin/hovrly/issues/3#issuecomment-1273269522
