### ISSUE TITLE
Feature Request: Timezone Tags

### ISSUE THREAD

**Issue by erikaraujo** [tarutin/hovrly#16]
As a full-remote worker, I have teammates all over the world and I add all of their timezones to Hovrly.

It would be nice to know what people are in what timezones, so, in order to be more generic, maybe it would be nice to be able to add "Tags" to the timezones.

I, personally, would use people's names as such tags, but maybe other people would have more use cases for it.

Anyways, just an idea.

**Comment by tarutin** [comment]
Renaming added in [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)

**Comment by erikaraujo** [comment]
Thanks, @tarutin !

So I guess tags are not really gonna be a thing? :(

In any case I can make do with renaming. Good job with hovrly, btw! 👏
