### ISSUE TITLE
I cant see black icon with a black theme 

### ISSUE THREAD

**Issue by dandaniel5** [tarutin/hovrly#17]
<img width="110" alt="image" src="https://user-images.githubusercontent.com/88844682/198332615-1ba654e6-6145-4094-831a-31249ddcdb93.png">
Also its didn't open with a full screen app. When i click a black icon its change desktop to one without "fullscreen app" and open there.

**Comment by tarutin** [comment]
Fixed [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
