### ISSUE TITLE
Text is black on a second monitor when it's not active

### ISSUE THREAD

**Issue by kovpas** [tarutin/hovrly#18]
<img width="377" alt="Screen Shot 2022-11-14 at 10 42 50" src="https://user-images.githubusercontent.com/1967999/201628028-833f89a1-351e-42bb-ba96-bad618b9f168.png">
<img width="407" alt="Screen Shot 2022-11-14 at 10 46 51" src="https://user-images.githubusercontent.com/1967999/201628247-d45cba48-c0b6-4b9e-8084-0516e958d8ae.png">

I've got a multi-monitor set up, and while the menu bar is visible on a non-active monitor, the icon is visible properly, but the text is not. It doesn't depend on the os theme as seen from the screenshots above, probably it should never be black...

**Comment by tarutin** [comment]
Fixed [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
