### ISSUE TITLE
Feature Request: Option+Click on Hovrly's Menu Bar Icon or Displayed Timezones...

### ISSUE THREAD

**Issue by Stickyhavr** [tarutin/hovrly#20]
Hello,
Most of the time I have two timezones displayed by Hovrly and then my system clock showing my local time in the top right corner of the menu bar. On multiple occasions I have tried to activate Do Not Disturb/Focus by option+clicking on Hoverly (instead of the Clock) by mistake and I was thinking it would be awesome if option+clicking on Hovrly also toggled DND. That way I could option click pretty much anywhere on the right side of my menu bar to activate it.

This sort of ties in with #4 in the sense that Hovrly could potentially replace the System Clock entirely (except that you can't actually do that in the latest versions of MacOS like you could Catalina and earlier—sigh).

Anyway, I have no idea if something like that would be easy to implement or not. If it is, then perhaps it would be nice to provide an option in the settings so that option+click could have multiple functions: either toggle Do Not Disturb, or it could temporarily toggle all Hoverly timezone from showing. In other words, the alternative configuration would make it so that you could hide your displayed timezones with one click and then when you wanted them all back, you could option+click the Hovrly menu bar icon again.

I find it easier to just quit Hovrly when I don't need it and then re-open it with Alfred/Spotlight when I need it again, so I wouldn't use the second option but I could see how some people might love the ability to quickly toggle. In any case, it seems like option+click should do something different than a normal click so hopefully this feature request will inspire your creativity. :-D

Thanks!

**Comment by tarutin** [comment]
@Stickyhavr no options in OS API(
