### ISSUE TITLE
Search completely not working

### ISSUE THREAD

**Issue by troelshartmann** [tarutin/hovrly#26]
I am on the latest version of the app on an M2 Pro Mac Mini, Ventura 13.2.

When I type any city into the Search bar and press enter, I get nothing, no error, no response, it just blanks out the Search field.

**Comment by tarutin** [comment]
@troelshartmann 
fixed

**Comment by troelshartmann** [comment]
Fixed, as in a new version or am I doing something wrong?

**Comment by parasshah195** [comment]
@tarutin Just installed it and it's not working for me either

**Comment by tarutin** [comment]
@parasshah195 @troelshartmann Hi! Fixed. Its just a database problem.
