### ISSUE TITLE
Timezone conversion via natural language

### ISSUE THREAD

**Issue by macintacos** [tarutin/hovrly#30]
It'd be cool if I could type something like "11am eastern" and have it convert all of the times in the app window to that time. Perhaps this is something that only shows up when you've hit "tab" in the main search box with no text in it, similar to how with the Fantastical widget you can switch from creating an event to searching your events by hitting "tab" while the window is open.

**Comment by tarutin** [comment]
@macintacos Thanks for idea. But now U can use time-slider
