### ISSUE TITLE
360mb and so much memory use for a fancy world clock???

### ISSUE THREAD

**Issue by avioli** [tarutin/hovrly#31]
I downloaded it, but didn't even install  it...

You've got to be kidding me - 360,048,283 bytes (360.3 MB on disk)

Can't you code it in Swift (with SwiftUI) - it will be a fraction of that size and possibly astronomically more memory efficient! They are also have some plans to have [Swift on Windows](https://www.swift.org/blog/swift-on-windows/) although no mention of SwiftUI for Win.

**Comment by tarutin** [comment]
@avioli yep, its ElectronJs 🤷‍♀️

I think about Swift. thanks
