### ISSUE TITLE
Should cities data get served over HTTPS

### ISSUE THREAD

**Issue by geftactics** [tarutin/hovrly#35]
I can see that city data comes from a mysql server (3306), which gets blocked by many corporate firewalls and VPNs... Also presumably ££$$ to operate.

json version of this data is currently 13MB, gzipped is 4.5k - So easily downloadable by the client.

Could potentially then just locally search the json? It's not a frequent activity, so the processing overhead shouldn't be a big issue?

This would allow the file to be served up from github/github-pages, or even just bundled with each release - eliminating issues of search not working for people.

Just a thought!

**Comment by tarutin** [comment]
@geftactics thanks for idea!
