### ISSUE TITLE
Feature request -> actual date

### ISSUE THREAD

**Issue by JulienVincenot** [tarutin/hovrly#4]
Hello

Besides the search problem (which I confirmed in the dedicated issue)
I think there's potential to Hovrly to completely replace the date/time item I always have in my menu bar.
The only thing missing is actually the date, which I often check.

Now this I think could have an interest when checking multiple time zones as well, to make sure you didn't make a mistake when setting up an appointment on a given date with colleagues.

Thanks for considering this !
Best,

Julien

**Comment by tarutin** [comment]
@JulienVincenot Thanks! Great idea! You'll see it in the next version! Hovrly has an auto-updater ;)

**Comment by JulienVincenot** [comment]
@tarutin Cool, happy you like it :) Looking forward to the update !

By the way I didn't check this yet this is coming in a few weeks, how does Hovrly behave regarding various daylight savings, + or - 1 hour in respective countries? In my experience this has also produced quite a mess for instance when teaching people abroad while being in France. Now I'm teaching people in France and other countries while being in China, can be quite tricky to make sure everyone is on the same page 😅

**Comment by tarutin** [comment]
@JulienVincenot I have 2 weeks to fix this problem)

**Comment by tarutin** [comment]
Added in [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)

**Comment by JulienVincenot** [comment]
Hi Alexey @tarutin 
It's been a while we had this exchange. I just checked in Hourly 2.4.5  and I'm not sure to understand what you changed besides adding a single date (the date where I am currently) in the menu item.
But when inside Hourly and moving the slider, there's no way to see which day / date it is in which city correct? 
That was my point, when you move the time the date changes in some countries. That's my main problem when scheduling Zoom classes across different time zones in US and Europe from China. Say I'm teaching on Wednesday morning but I have to think that's Tuesday evening in NYC, etc.
Thanks !
