### ISSUE TITLE
Feature Request: Install via Homebrew

### ISSUE THREAD

**Issue by kolchurinvv** [tarutin/hovrly#5]
pretty please! 😃

**Comment by tarutin** [comment]
@kolchurinvv 
ok!

My todo: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by kolchurinvv** [comment]
@tarutin would you like some help with this?

**Comment by tarutin** [comment]
@kolchurinvv Yes, Firstable I need create the formulae in Homebrew?

**Comment by kolchurinvv** [comment]
Tbh, I haven't done this before either. let me go through their docs and i'll post here what i find!

**Comment by rognales** [comment]
guys, any update on this? Would love to have this feature so we can integrate it with our dotfiles

**Comment by kolchurinvv** [comment]
None yet. my 9-5 needed some more attention than usual lately (database normalization + migration + adapting to destructured data format - you get the idea). i'll spend some time this week maybe to start chipping away at this

**Comment by tarutin** [comment]
@kolchurinvv @rognales 

Done.

```
brew update
brew install hovrly
```
