### ISSUE TITLE
Feature request: Option to hide the Icon

### ISSUE THREAD

**Issue by unterhauser** [tarutin/hovrly#6]
It would be great to have an option to hide the filled circle completely from the task bar as it doesn't really add any benefit and is quite attention grabbing. By doing so and only displaying the timezones, it would actually look more seamlessly integrated, just like a native MacOS feature.

**Comment by tarutin** [comment]
@unterhauser  Thanks! Great idea! You'll see it in the next version! Hovrly has an auto-updater ;)

**Comment by unterhauser** [comment]
awesome news! thanks, really great tool for people working remotely in different timezones

**Comment by tarutin** [comment]
Added in [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
