### ISSUE TITLE
Text in task bar turns black on inactive monitor (dark mode)

### ISSUE THREAD

**Issue by unterhauser** [tarutin/hovrly#7]
![SCR-20221010-g5e](https://user-images.githubusercontent.com/26206671/194838046-87c20e7d-c4f5-442b-a4b6-cfc13774df20.png)
I'm working on a dual monitor setup, but on the inactive monitor (where it lowers the opacity of all task bar elements) it will always switch the timezones text to black instead of keeping it white. This is a bit distracting and I'm sure not intentional. Would be great to get this fixed in a new update. See my attached screenshot for reference.

**Comment by tarutin** [comment]
@unterhauser 
Can you write this information:
- Macbook model and year
- MacOS version

**Comment by unterhauser** [comment]
For sure. It's a MBP 14" with M1 Max (2021) running macOS Monterey 12.6

**Comment by jimmysmits** [comment]
This is the same issue as in #2, see also my comment there, now I think of it - I think the menu bar switched to white text when I plugged in a second monitor

**Comment by tarutin** [comment]
#2
