### ISSUE TITLE
Feature Request: IATA Airport Codes

### ISSUE THREAD

**Issue by ExHongKonger** [tarutin/hovrly#9]
Thanks for the great app, and for responding so quickly to fix issues!

Would it be possible to add an option to use IATA airport codes for cities (For example CKG for Chongqing, rather than CHO) in the 'compact view'? 

I realize there might be potential issues with cities such as Tokyo, London, New York, etc. that have multiple airports which might require an additional selection.  

Here's a list of codes put together by nationsonline.org:
https://www.nationsonline.org/oneworld/IATA_Codes/airport_code_list.htm

**Comment by tarutin** [comment]
@ExHongKonger Hi again) Maybe you are the pilot?)) I`ll think about it! In my opinion cities are more relevant for searching and more friendly for people. Curious to know what do you think about it :)

**Comment by ExHongKonger** [comment]
Hi!

I'm not a pilot, but I spend far too much time on planes, so I tend to remember cities by their airport codes.  I agree that most people would probably prefer the city name, but it might be a nice option for frequent flyers.

**Comment by tarutin** [comment]
@ExHongKonger done. 9,766 IATA Airport Codes added!
